language: python
python: 3.6
cache: pip
env:
  - TOX_ENV=py36
  - TOX_ENV=flake8
install:
  - pip install tox
  - pip install kinto kinto-wizard
  - kinto init --backend memory
before_script:
  - kinto start &
  # Wait for the service to have started.
  - sleep 3
script:
  - cd jobs; tox -e $TOX_ENV
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
matrix:
  include:
    - language: node_js
      node_js: 7
      install:
        - cd ui
        - npm install
      before_script:
      script:
        - npm run build
      cache:
        directories:
          - "node_modules"
