language: python
python: 3.6
cache: pip
matrix:
  include:
    - language: python
      install:
        - pip install tox
      script:
        - cd jobs; tox -e flake8

    - language: python
      install:
        - pip install tox
        - pip install kinto kinto-wizard
        - kinto init --backend memory
      before_script:
        - kinto start &
        - sleep 3; kinto-wizard load jobs/buildhub/initialization.yml --server http://localhost:8888/v1 --auth user:pass
      script:
        - cd jobs; tox -e py36
      after_success:
        # Report coverage results to coveralls.io
        - pip install coveralls
        - coveralls

    - language: node_js
      node_js: 7
      install:
        - cd ui
        - npm install
      before_script:
      script:
        - npm run build
      cache:
        directories:
          - "node_modules"
